###

POST localhost:8080/clothes
Content-Type: application/json

{
  "brand": "guzzi",
  "gender": "MALE",
  "imageUrl": "https://www.guzzi.com/it_IT/heritage/v7-iii/v7-iii-stone",
  "clothesCategory": "TOP",
  "name": "ABC",
  "sellUrl": "https://www.guzzi.com/it_IT/heritage/v7-iii/v7-iii-stone"
}

###

POST localhost:8080/clothes
Content-Type: application/json

{
  "brand": "hazzi",
  "gender": "MALE",
  "imageUrl": "https://www.guzzi.com/it_IT/heritage/v7-iii/v7-iii-stone",
  "clothesCategory": "BOTTOM",
  "name": "EFD"
}


###
GET localhost:8080/clothes