###

POST localhost:8080/clothes
Content-Type: application/json

{
  "brand": "guzzi",
  "gender": "MALE",
  "imageUrl": "https://www.guzzi.com/it_IT/heritage/v7-iii/v7-iii-stone",
  "clothesCategory": "TOP",
  "name": "ABC",
  "sellUrl": "https://www.guzzi.com/it_IT/heritage/v7-iii/v7-iii-stone"
}

###

POST localhost:8080/clothes
Content-Type: application/json

{
  "brand": "hazzi",
  "gender": "MALE",
  "imageUrl": "https://www.guzzi.com/it_IT/heritage/v7-iii/v7-iii-stone",
  "clothesCategory": "BOTTOM",
  "name": "11월일에 만든"
}


###
# 단순 조회
GET localhost:8080/clothes

###
# 사이즈 조정
GET localhost:8080/clothes?size=100

###
# clothesCategory 추가
GET localhost:8080/clothes?clothesCategory=BOTTOM
