###

GET localhost:8080/posts


###

GET localhost:8080/posts?celebCategory=ACTOR


###

GET localhost:8080/posts?gender=MALE


###


GET localhost:8080/posts?search=이것이 title!

###

GET localhost:8080/posts?search=박보영&celebCategory=ACTOR


###

GET localhost:8080/posts?userId=2

###

POST localhost:8080/posts
Content-Type: application/json

{
  "title": "이것이 title!",
  "clothesIdList": [
    1,
    5
  ],
  "userId": 2,
  "imageUrl": "naver.com",
  "celebId": 6,
  "gender": "FEMALE"
}
