###

GET localhost:8080/posts


###

GET localhost:8080/posts?celebCategory=SINGER



###


GET localhost:8080/posts?search=이승기

###

GET localhost:8080/posts?search=이승기&celebCategory=ACTOR


###

GET localhost:8080/posts?userId=2

###

POST localhost:8080/posts
Content-Type: application/json

{
  "title": "유저아이디2",
  "content": "진짜..",
  "clothesIdList": [
    1,
    2
  ],
  "userId": 2,
  "imageUrl": "naver.com",
  "celebId": 5
}
